//
//  ZooPlantInfoTest.swift
//  SKBankInterviewTaskTests
//
//  Created by 張文煥 on 2023/6/19.
//

import XCTest

final class ZooPlantInfoTest: XCTestCase {

    override func setUpWithError() throws {
        try super.setUpWithError()
    }
    
    override func tearDownWithError() throws {
        try super.tearDownWithError()
    }
    
    func testZooPlantInfo() {
        let json = getResultJsonString()
        let data = json.data(using: .utf8)!
        let result = try? JSONDecoder().decode(GetZooPlantInfoResponse.self, from: data)

        XCTAssertEqual(result?.result.results.count, 20)
        XCTAssertEqual(result?.result.results[0].id, 1)
        XCTAssertEqual(result?.result.results[0].﻿name, "九芎")
        XCTAssertEqual(result?.result.results[0].location, "臺灣動物區；蟲蟲探索谷；熱帶雨林區；鳥園；兩棲爬蟲動物館")
        XCTAssertEqual(result?.result.results[19].family, "菊科Asteraceae")
        
    }
    
    func getResultJsonString() -> String {
        let resultJson = #"""
        {
            "result": {
                "limit": 20,
                "offset": 0,
                "count": 220,
                "sort": "",
                "results": [
                    {
                        "_id": 1,
                        "﻿F_Name_Ch": "九芎",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "苞飯花、拘那花、小果紫薇、南紫薇、猴不爬、怕癢樹、南紫薇、九荊、馬鈴花、蚊仔花",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216),  (121.5805328 24.9959671),  (121.5836763 24.9957094),  (121.5894029 24.9951126),  (121.5899205 24.9945669))",
                        "F_Location": "臺灣動物區；蟲蟲探索谷；熱帶雨林區；鳥園；兩棲爬蟲動物館",
                        "F_Name_En": "Subcostate Crape Myrtle",
                        "F_Name_Latin": "Lagerstroemia subcostata",
                        "F_Family": "千屈菜科 Lythraceae",
                        "F_Genus": "紫薇屬Lagerstroemia",
                        "F_Brief": "分布於中低海拔森林及長江以南的地區，為台灣的原生樹種。主要生長在潮濕的崩塌地，有吸水保持土壤之特性，所以是良好的水土保持樹種。",
                        "F_Feature": "紅褐色的樹皮剝落後呈灰白色，樹幹光滑堅硬。葉有極短的柄，長橢圓形或卵形，全綠，葉片兩端尖，秋冬轉紅。夏季6～8月開花，花冠白色，花數甚多而密生於枝端，花為圓錐花序頂生，花瓣有長柄，邊緣皺曲像衣裙的花邊花絲長短不一。果實為蒴果，橢圓形約6-8公厘，種子有翅。",
                        "F_Function＆Application": "1. 優良薪炭材：木質堅硬耐燒，是臺灣優良的薪炭材之一。\n2. 水土保持植栽：可栽植於河岸及邊坡供水土保持。\n3. 農具用材：木質堅硬，乾燥後不太會反翹，是做農具的用材。\n4. 食用性：花、根入藥，味淡微苦，敗毒散瘀，花蕾味苦有清香，可生食。葉子是長尾水青蛾幼蟲的食草。",
                        "F_Code": "",
                        "F_Pic01_ALT": "九芎果實",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Lythraceae/subcostata/subcostata_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 2,
                        "﻿F_Name_Ch": "大安水蓑衣",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "竄心蛇、魚骨草、九節花、毛萼水蓑衣、墨菜",
                        "F_Geo": "MULTIPOINT ((121.5843697 24.9951552), (121.5817425 24.9980128), (121.5807098 24.9965943))",
                        "F_Location": "蟲蟲探索谷；水生植物園；白手長臂猿島",
                        "F_Name_En": "Da-Ann hygrophila",
                        "F_Name_Latin": "Hygrophila pogonocalyx",
                        "F_Family": "爵床科Acanthaceae",
                        "F_Genus": "水蓑衣屬Hygrophila",
                        "F_Brief": "臺灣特有種，生存條件並不嚴苛，長期積水的溼地即可生存，即便在冬季也能開花。因環境遭受破壞，野生族群銳減，僅剩臺中沿海有分佈，其他區域所見的幾乎為人工栽植。",
                        "F_Feature": "水生草本植物。莖直立呈方形，全株多毛。葉長度9公分，寬度1公分，呈披針形或橢圓形，質感類似紙張，雙面皆有白色粗毛。花呈淡紫色，集中開在葉柄與莖的接合處，花朵有上下兩片花瓣類似嘴唇，上唇較小，下唇較大，雄蕊有4枚，兩長兩短。果實呈細長圓柱狀。",
                        "F_Function＆Application": "1. 教學用水生植物、觀賞用：大安水蓑衣為臺灣瀕臨絕種之珍稀植物，因而常被學校種植作為指標性水生植物。",
                        "F_Code": "",
                        "F_Pic01_ALT": "淡紫色的花種植於水池中顯得格外亮眼",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Acanthaceae/pogonocalyx/pogonocalyx_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "1"
                    },
                    {
                        "_id": 3,
                        "﻿F_Name_Ch": "大花紫薇",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "爆炸樹、大果紫薇、大葉紫薇、洋紫薇、百日紅",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216),  (121.5805328 24.9959671),  (121.582185 24.9984662),  (121.5836763 24.9957094),  (121.5816861 24.9980966))",
                        "F_Location": "臺灣動物區；蟲蟲探索谷；兒童動物區；熱帶雨林區；白手長臂猿島",
                        "F_Name_En": "Queen lagerstroemia、Queen crape myrtle",
                        "F_Name_Latin": "Lagerstroemia speciosa",
                        "F_Family": "千屈菜科Lythraceae",
                        "F_Genus": "紫薇屬Lagerstroemia",
                        "F_Brief": "原產於澳洲、熱帶亞洲。生長快速，木材堅硬，耐腐力強，色紅而光亮，價值媲美柚木。",
                        "F_Feature": "落葉喬木，可高達25公尺，樹幹通直，樹皮光滑，呈片狀剝落。單葉對生，革質，葉呈長橢圓形，長度10~28公分，寬度5~12公分，脫落前會變紅。花朵直徑5~8公分，花瓣有6枚，長度2.5~3.5公分，接近圓形，邊緣呈不規則波浪狀，早上初開時呈紅色，傍晚轉為紫紅色。果實直徑約3.5公分，呈球形，分裂成6瓣，初生時呈綠色，成熟時轉褐色。種子扁平具有翅，有利隨風散播。",
                        "F_Function＆Application": "1. 園藝景觀植栽用：花大、美麗，開花時，花團錦簇，甚為壯觀。秋季滿樹金黃的葉子，常栽培於庭園供觀賞或作行道樹用。\n2. 木材用途：木材堅硬，耐腐力強，色紅而亮，在原產地常被用於家具、舟車、橋樑、電杆、枕木及建築，也作水中用材。",
                        "F_Code": "",
                        "F_Pic01_ALT": "由數小朵花朵聚成一團甚為壯觀",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Lythraceae/speciosa/speciosa_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 4,
                        "﻿F_Name_Ch": "大葉溲疏",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "白埔姜、常山、百祥花、大花溲疏、美麗溲疏",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216),  (121.5836763 24.9957094))",
                        "F_Location": "臺灣動物區；熱帶雨林區",
                        "F_Name_En": "Evergreen deutzia",
                        "F_Name_Latin": "Deutzia pulchra",
                        "F_Family": "虎耳草科Saxifragaceae",
                        "F_Genus": "溲疏屬Deutzia",
                        "F_Brief": "分布於菲律賓呂宋島北部及臺灣，在臺灣主要分布於中高海拔山區，蘭嶼也有。",
                        "F_Feature": "可為灌木或小喬木。葉呈卵形至長橢圓形，質地如皮革，雙面皆有星狀鱗片貼伏，上表面呈暗綠色，下表面則呈淡綠色。花穗可長達15公分，花軸多毛，花朵眾多，花瓣長度12公厘，寬度3公厘，呈白色披針形，雄蕊與花瓣大致等長。",
                        "F_Function＆Application": "1.園藝用途：花潔白、有淡香味，可作庭植添景樹，花、果枝則供作花材。",
                        "F_Code": "",
                        "F_Pic01_ALT": "花開後有淡香深受人們喜愛",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Saxifragaceae/pulchra/pulchra_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 5,
                        "﻿F_Name_Ch": "大艷紅赫蕉",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "大蠍尾蕉、龍蝦爪",
                        "F_Geo": "MULTIPOINT ((121.5908284 24.9952998))",
                        "F_Location": "鳥園",
                        "F_Name_En": "Red palulu、Macawflower、Balisier",
                        "F_Name_Latin": "Heliconia bihai ",
                        "F_Family": "赫蕉科Heliconiaceae",
                        "F_Genus": "赫蕉屬Heliconia",
                        "F_Brief": "原產於北美洲和西印度群島。在巴西北部和瓜亞那相當常見。該植物在潮濕炎熱的氣候下常作為觀賞植物。",
                        "F_Feature": "單葉對生，長橢圓形，先端漸尖，葉基鈍，全緣葉，革質，葉面翠綠，葉脈中肋清晰，中肋於背面隆起，側脈平行，具長柄，葉鞘包莖，聚繖花序，自莖中抽出花莖，直立狀，苞片排列於花序柄兩側，折疊如船形，花小，花色為黃白或黃綠，蒴果，綠色，囊狀，種子細小。",
                        "F_Function＆Application": "1.適合庭園叢植、美化。",
                        "F_Code": "",
                        "F_Pic01_ALT": "大艷紅赫蕉",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Heliconiaceae/bihai/bihai_1.jpg",
                        "F_Pic02_ALT": "紅色的花宛如小杯子一樣往上堆疊",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Heliconiaceae/bihai/bihai_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "2"
                    },
                    {
                        "_id": 6,
                        "﻿F_Name_Ch": "小葉王蓮",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "巴拉圭王蓮、阿根廷王蓮、克魯茲王蓮",
                        "F_Geo": "MULTIPOINT ((121.5843563 24.9951527))",
                        "F_Location": "水生植物園",
                        "F_Name_En": "Santa Cruz water lily、Water platter、Yrupe",
                        "F_Name_Latin": "Victoria cruziana",
                        "F_Family": "睡蓮科Nymphaeaceae",
                        "F_Genus": "王蓮屬Victoria",
                        "F_Brief": "為熱帶物種的開花植物，原產於南美洲的阿根廷和巴拉圭。此為植物園中普遍受歡迎的水中植物，可生長在較冷的水域。",
                        "F_Feature": "單葉互生，葉圓形，全緣或有齒，邊緣向上折轉或直立，高7~10公分，葉直徑可達1~3公尺，葉面深綠或綠色，肉質有光澤，無刺網狀脈，葉脈隆起；葉背常深紅色，有突起網狀葉脈，脈上具2~3公分長之尖皮刺，刺為淺褐色；葉柄長，淺褐色，粗壯，密佈粗刺，刺淺褐色。兩性花，單出，生於葉腋處，挺出水面，入夜開花，顏色變淡紅至深紅色。果實為漿果，球形，在水中成熟，結實多，黑色。",
                        "F_Function＆Application": "1. 觀賞用：適合水池栽培，常用於植物園、公園等水景佈置。\n2. 食用：果實外型如玉米，因而又稱「水中玉米」。種子含多量澱粉、少量蛋白質、脂肪油及微量的鈣、磷、鐵、核黃素、維生素C等養分，在原產地長久以來就被當做食物，用途接近「芡實」。",
                        "F_Code": "",
                        "F_Pic01_ALT": "表面巨大且漂浮於水面上像一葉扁舟",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Nymphaeaceae/cruziana/cruziana_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "3"
                    },
                    {
                        "_id": 7,
                        "﻿F_Name_Ch": "小葉南洋杉",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "南洋杉、異葉南洋杉、諾和克南洋杉",
                        "F_Geo": "MULTIPOINT ((121.5847425 24.9949157), (121.5899152 24.9951418), (121.5898441 24.9933781))",
                        "F_Location": "水生植物園；鳥園；溫帶動物區",
                        "F_Name_En": "Norfolk island pine、Star pine",
                        "F_Name_Latin": "Araucaria heterophylla",
                        "F_Family": "南洋杉科Araucariaceae",
                        "F_Genus": "南洋杉屬Araucaria",
                        "F_Brief": "外來植物，原產於澳洲外海的諾福克島(Norfolk Island)。樹形優美，為世界知名園景樹種，除了行道樹，亦可種植於盆栽，幼株可充當聖誕樹。",
                        "F_Feature": "常綠喬木，樹形如同尖塔，側枝水平開展。葉成針狀，但不刺手。毬果呈球形，直徑10~12公分，雌雄異珠，毬果皆長於枝條末端。種子具有翅膀，有利隨風飄散。",
                        "F_Function＆Application": "1. 觀賞綠化樹種：為世界最優美的庭園觀賞樹之一，常被栽種為行道樹、公園樹、庭園造景。全株均有臘質被覆保護，對潮風及鹽分的抵抗力極強，適合種植為海岸景觀樹。\n2. 木材可供建築、器具、家具等使用。",
                        "F_Code": "",
                        "F_Pic01_ALT": "小葉南洋杉",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Araucariaceae/heterophylla/heterophylla_1.jpg",
                        "F_Pic02_ALT": "葉成針狀柔順但不刺手",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Araucariaceae/heterophylla/heterophylla_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "4"
                    },
                    {
                        "_id": 8,
                        "﻿F_Name_Ch": "小葉桑",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "桑樹、蠶仔葉樹、桑材子、桑仔樹、娘子樹、小桑樹、梁樹、鹽桑仔、雞桑、桑白、野桑、島桑",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5808258 24.9981769), (121.5805328 24.9959671), (121.582185 24.9984662), (121.5836763 24.9957094), (121.5840572 24.9949801), (121.5855083 24.9951041), (121.5855083 24.9944599), (121.5867072 24.9945377), (121.5897274 24.9950725), (121.5902638 24.9927776), (121.5816861 24.9980966), (121.5819168 24.9978147), (121.5805221 24.9966478), (121.5808976 24.9974476), (121.5819651 24.9993218), (121.5826839 24.9982255), (121.5830863 24.9973285), (121.5836763 24.9957094), (121.5847546 24.9955879), (121.5899205 24.9945669), (121.590929 24.9930645), (121.5831023,24.9970222), (121.5811899 24.9986995))",
                        "F_Location": "全園普遍分佈",
                        "F_Name_En": "Small-leaved mulberry、Japanese mulberry、Taiwan mulberry",
                        "F_Name_Latin": "Morus australis ",
                        "F_Family": "桑科Moraceae",
                        "F_Genus": "桑屬  Morus",
                        "F_Brief": "分布於中國、韓國、日本、琉球群島、越南、印度、印尼及臺灣，在臺灣廣泛分布，海拔上限為1500公尺。",
                        "F_Feature": "為落葉小喬木或大型灌木，枝條具有黃灰色的皮孔用於呼吸。葉片長10~15公分，寬6~9公分，呈廣卵形，邊緣呈尖銳鋸齒狀。花朵為單一性別，單一植株只會開特定性別的花。果實俗稱桑椹，長度2~2.5公分，呈長橢圓形，為多顆瘦果組成，成熟呈暗紅色或深紫色。",
                        "F_Function＆Application": "1. 庭園造景：作綠籬、庭園美化、盆栽，單植、行植或列植均可。\n2. 食用：果可生食，除為野鳥食物，也能製成果汁蜜餞等食品。葉為家?食草。\n3. 造紙原料及繩索：取樹皮內皮纖維部份，可作造紙纖維和編製繩索的材料。",
                        "F_Code": "",
                        "F_Pic01_ALT": "葉片普通不易辨認",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Moraceae/australis/australis_1.jpg",
                        "F_Pic02_ALT": "剛長出的桑葚果為嫩綠色",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Moraceae/australis/australis_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 9,
                        "﻿F_Name_Ch": "山月桃",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "中位月桃、山月桃仔、紅三七、七葉蓮、小月桃",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216))",
                        "F_Location": "臺灣動物區",
                        "F_Name_En": "Small shellflower",
                        "F_Name_Latin": "Alpinia intermedia",
                        "F_Family": "薑科Zingiberaceae",
                        "F_Genus": "月桃屬Alpinia",
                        "F_Brief": "分布於菲律賓、琉球、日本及臺灣，在臺灣分布於海拔300~1000公尺森林底層。",
                        "F_Feature": "草本植物，植株高度1公尺，終年常綠。葉長25~30公分，寬6~8公分，兩面光滑，邊緣多毛。花穗直立，花軸柔軟，長10~20公分，花穗每條分支開3~4朵花，每朵花有3片花瓣。果實呈球形，橘紅色，表面光滑。",
                        "F_Function＆Application": "1. 莖葉有韌性，可做繩索。\n2. 花果美觀，可作庭園景觀植物。",
                        "F_Code": "",
                        "F_Pic01_ALT": "莖葉叢生",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Zingiberaceae/intermedia/intermedia_1.jpg",
                        "F_Pic02_ALT": "雪白的花穗中帶著粉紅色格外漂亮",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Zingiberaceae/intermedia/intermedia_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 10,
                        "﻿F_Name_Ch": "山芙蓉",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "臺灣芙蓉、狗頭芙蓉、三醉芙蓉、酸芙蓉、臺灣山芙蓉、千面美人、千面女娘、拒霜花",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5805328 24.9959671), (121.5902638 24.9927776))",
                        "F_Location": "臺灣動物區；蟲蟲探索谷；溫帶動物區",
                        "F_Name_En": "Taiwan?cotton-rose",
                        "F_Name_Latin": "Hibiscus taiwanensis",
                        "F_Family": "錦葵科Malvaceae",
                        "F_Genus": "木槿屬Hibiscus",
                        "F_Brief": "臺灣特有種，分布海拔上限2000公尺。",
                        "F_Feature": "灌木，葉柄及花梗有少許短毛。葉長7~9公分，質感類似紙張，呈廣卵形，有3~7裂片，但也有部份葉片並未分裂，葉柄長達10~16公分，表面多毛。花朵直徑6~9公分，形狀類似鈴鐺，單生，開在葉柄與莖的接合處，花瓣寬度4~5公分，接近圓形，表面多毛。果實直徑3.5公分，表面多毛。",
                        "F_Function＆Application": "1. 庭園觀賞用：清晨花朵綻放時是白色或粉紅色，到了午後至傍晚凋落前，則轉為紫紅色或粉紅色。\n2. 食用：花可食用，沙拉、炒食或油炸均可。\n3. 木屐、繩索：木材色白質輕軟，主幹粗大可供製木屐；樹皮含纖維，在野外求生或露宿時，可替代繩索用。",
                        "F_Code": "",
                        "F_Pic01_ALT": "花朵的形狀乍看下如同芙蓉一般",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Malvaceae/taiwanensis/taiwanensis_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 11,
                        "﻿F_Name_Ch": "尤加利",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "桉樹、大葉尤加利、蚊子樹、大葉桉",
                        "F_Geo": "MULTIPOINT ((121.5840572 24.9949801), (121.5855083 24.9944599), (121.5816861 24.9980966), (121.5826839 24.9982255))",
                        "F_Location": "水生植物園；澳洲動物區；溫帶動物區；無尾熊館",
                        "F_Name_En": "Eucalyptus、?blue gum、 gum tree",
                        "F_Name_Latin": "Eucalyptus spp.",
                        "F_Family": "桃金孃科Myrtaceae",
                        "F_Genus": "桉屬Eucalyptus",
                        "F_Brief": "為澳洲木本植物中具代表性的樹種。在已知的七百多種桉樹中，絕大多數生長在澳洲，少部分生長於鄰近的紐幾內亞島和印度尼西亞，以及一種遠在菲律賓群島。",
                        "F_Feature": "常綠植物，一年?有周期性的老葉?落現象。大多數是高大喬木，少數是小喬木，呈灌木狀的很少。樹冠形狀有尖塔形、多枝形和垂枝形等。單葉，全緣，革質，有時被有一層薄蠟質。葉子可分?幼態葉、中間葉和成熟葉三類，大多數的幼態葉是對生的，較小，心臟形或闊披針形。",
                        "F_Function＆Application": "1.澳洲東部的30至50種桉樹，其樹葉為澳洲特有種動物無尾熊的唯一食物來源。其中細葉桉和脂桉可說是無尾熊的主食，二者約占40 %；大葉桉、小果灰桉和灰桉是次要食物，三者約占40%；樹膠桉、斑桉和白桉更次一級，三者約占20 %；至於山藍桉和赤桉只能算是點心食物，解饞之用。尤其山藍桉是提煉尤加利樹精油的主要來源。",
                        "F_Code": "",
                        "F_Pic01_ALT": "無尾熊最愛吃的樹葉",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Myrtaceae/spp/spp_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 12,
                        "﻿F_Name_Ch": "方莖金絲桃",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "絲海棠、土連翹、小汗淋草、小過路黃、小對月草、貫葉連翹、小對葉草、聖約翰草",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5836763 24.9957094))",
                        "F_Location": "臺灣動物區；熱帶雨林區",
                        "F_Name_En": "Four-angled Stem",
                        "F_Name_Latin": "Hypericum subalatum",
                        "F_Family": "金絲桃科Guttiferae",
                        "F_Genus": "金絲桃屬Hypericum",
                        "F_Brief": "臺灣特有種，分布於海拔400~900公尺的石灰岩裂縫，如新北市新店、宜蘭龜山島及花蓮縣。",
                        "F_Feature": "灌木，莖呈方形。葉片沒有葉柄，長2~7公分，寬0.5~1.5公分，呈長橢圓形，上表面具有明顯的灰白色油腺點。枝條末端通常開1~3朵花，葉柄與莖的接合處偶爾會開多達12朵花，花朵直徑2.5公分，花瓣長1~1.2公分，寬6~7公厘，呈黃色；雄蕊具有琥珀色腺體，每朵花有5束雄蕊，每束有15枚雄蕊，共有75枚。果實長7~9公厘，寬3~4公厘，形狀類似狹長的雞蛋或圓柱體。",
                        "F_Function＆Application": "1. 觀賞用：花朵於四~五月盛開。",
                        "F_Code": "",
                        "F_Pic01_ALT": "盛開的金絲桃花朵相當搶眼",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Guttiferae/subalatum/subalatum_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 13,
                        "﻿F_Name_Ch": "日本女貞",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "琉球女貞、女貞木、冬青木、東女貞、女真花、凍青樹、毛貞木、毛女貞、鈍頭女貞、苦丁茶、苦茶葉",
                        "F_Geo": "MULTIPOINT ((121.5897274 24.9950725), (121.5902638 24.9927776))",
                        "F_Location": "鳥園； 溫帶動物區",
                        "F_Name_En": "Hairy japanese privet、Japanese privet",
                        "F_Name_Latin": "Ligustrum japonicum",
                        "F_Family": "木樨科Oleaceae",
                        "F_Genus": "女貞屬Ligustrum",
                        "F_Brief": "分布於中國、韓國、日本、琉球群島、小笠原群島及臺灣，在臺灣主要分布於北部及中部海拔1000~3000公尺的山區。",
                        "F_Feature": "灌木，高度可達3公尺。葉長2.5~6公分，寬1.5~3公分，呈廣卵形或長卵形，質地如皮革，光滑無毛，終年維持綠色不落葉。花開在枝條末端，花軸長6~15公分，表面光滑無毛或僅有短茸毛。",
                        "F_Function＆Application": "1. 庭園樹、綠籬、盆栽。\n2. 食用：新芽及嫩葉可供食用，略帶苦味。\n3. 種子可供泡茶飲用：具有強身效果。",
                        "F_Code": "",
                        "F_Pic01_ALT": "日本女貞",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Oleaceae/japonicum/japonicum_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 14,
                        "﻿F_Name_Ch": "日本矮竹",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "五葉竹、倭竹、崗姬竹",
                        "F_Geo": "MULTIPOINT ((121.5905817 24.9925467),  (121.5832244 24.9969128))",
                        "F_Location": "溫帶動物區；保育大道(主軸)",
                        "F_Name_En": "Ruscus-leaved bamboo、Okame-zasa",
                        "F_Name_Latin": "Shibataea kumasasa",
                        "F_Family": "禾本科Gramineae",
                        "F_Genus": "崗姬竹屬 Shibataea　",
                        "F_Brief": "分布於日本，在臺灣廣泛栽植作為造景植物。",
                        "F_Feature": "小型竹類，高度僅20~100公分，直徑2~5公厘。竹節非常明顯，節長3~10公分，每節有2~6條柔軟枝條。竹籜質感類似紙張，厚度極薄，邊緣有白色毛。竹葉長0.5~1公分，寬1.2~2.5公分，葉柄長度0.5公分。花穗長15~18公厘，開兩朵花。果實長7公厘，直徑4公厘，呈圓柱狀。",
                        "F_Function＆Application": "1. 庭栽或盆栽觀賞、綠籬植物。",
                        "F_Code": "",
                        "F_Pic01_ALT": "低矮型竹類適合作綠籬植物",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Gramineae/kumasasa/kumasasa_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "5"
                    },
                    {
                        "_id": 15,
                        "﻿F_Name_Ch": "月桃",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "草蔻、大草蔻、豔山薑、玉桃、良薑、草荳蔻、虎子花",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5808258 24.9981769), (121.5805328 24.9959671), (121.582185 24.9984662), (121.5836763 24.9957094), (121.5840572 24.9949801), (121.5855083 24.9951041), (121.5855083 24.9944599), (121.5867072 24.9945377), (121.5897274 24.9950725), (121.5902638 24.9927776), (121.5816861 24.9980966), (121.5819168 24.9978147), (121.5805221 24.9966478), (121.5808976 24.9974476), (121.5819651 24.9993218), (121.5826839 24.9982255), (121.5830863 24.9973285), (121.5836763 24.9957094), (121.5847546 24.9955879), (121.5899205 24.9945669), (121.590929 24.9930645), (121.5831023,24.9970222), (121.5811899 24.9986995))",
                        "F_Location": "全園普遍分佈",
                        "F_Name_En": "Shell flower、Showy galangal",
                        "F_Name_Latin": "Alpinia zerumbet",
                        "F_Family": "薑科Zingiberaceae",
                        "F_Genus": "月桃屬Alpinia",
                        "F_Brief": "分布於中國大陸、海南島、馬來西亞、印尼爪哇島、臺灣、關島及日本",
                        "F_Feature": "植株高2~3公尺。葉片長60~70公分，寬10~15公分，呈長披針形，葉面光滑，邊緣長有濃密細毛。花穗長25~30公分，有分節，通常下垂，花軸多毛，花梗長1~2公分，每條花梗通常開2朵花，花朵長2.5公分，呈白色或粉紅色。果實呈球狀，成熟時由綠色轉深紅色，會不規則裂開。",
                        "F_Function＆Application": "1. 觀賞、插花花材用：花朵似翩翩飛舞的蝴蝶，非常搶眼。\n2. 莖狀的葉鞘，曬乾後編製成草蓆或繩索；月桃葉可包粽子；種子做「仁丹」。\n3. 蝴蝶幼蟲的食草：有三種蝴蝶的幼蟲以月桃維生，其中黑鳳蝶及大白紋蝶食用它的葉片，而白波紋小灰蝶則取食它的花序。",
                        "F_Code": "",
                        "F_Pic01_ALT": "與山月桃為叢生生長植物",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Zingiberaceae/zerumbet/zerumbet_1.jpg",
                        "F_Pic02_ALT": "花穗外觀如像米穗般",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Zingiberaceae/zerumbet/zerumbet_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 16,
                        "﻿F_Name_Ch": "水冬瓜",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "水冬哥、水東哥、水管心、火筒棒、倒吊風、大冇樹",
                        "F_Geo": "MULTIPOINT ((121.5808258 24.9981769), (121.5805221 24.9966478), (121.5805328 24.9959671), (121.5840572,24.9949801), (121.5831023,24.9970222))",
                        "F_Location": "蕨園；昆蟲館；蟲蟲探索谷；水生植物園；保育大道(主軸)",
                        "F_Name_En": "Oldham's Saurauia",
                        "F_Name_Latin": "Saurauia oldhamii ",
                        "F_Family": "獼猴桃科Actinidiaceae",
                        "F_Genus": "水冬瓜屬Saurauia",
                        "F_Brief": "分布於中國南部、琉球及臺灣，在臺灣分布於海拔300~1700公尺的闊葉林。",
                        "F_Feature": "可為小喬木或灌木，終年常綠，幼小枝條表面多毛。葉長15~20公分，寬6~8公分，呈披針形至倒披針形，上表面光滑無毛，葉柄柔軟，長2~3公分。花朵直徑僅1公分，花梗長度僅4公厘，每朵花有5枚花瓣，3枚雌蕊。果實為白色球形莓果，厚1公分。",
                        "F_Function＆Application": "1. 食用：果實成熟時會呈現晶瑩剔透的乳白色，咬下去感覺溼溼粘粘的但味道甜美，原住民戲稱為「好吃的鼻涕」。根可以治腹痛、感冒；將嫩葉搗碎還可以用來治刀傷、火傷和跌打損傷。",
                        "F_Code": "",
                        "F_Pic01_ALT": "果實可當緊急野果食用",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Actinidiaceae/oldhamii/oldhamii_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 17,
                        "﻿F_Name_Ch": "水車前",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "龍舌草、水車前草、水白菜",
                        "F_Geo": "MULTIPOINT ((121.5845883 24.9950057))",
                        "F_Location": "水生植物園",
                        "F_Name_En": "Water-plantain ottelia",
                        "F_Name_Latin": "Ottelia alismoides",
                        "F_Family": "水鱉科Hydrochiaritaceae",
                        "F_Genus": "水鱉屬Hydrocharis",
                        "F_Brief": "分布於澳洲、馬來西亞、琉球群島至日本。靜止或流動淡水域皆可適應，全株沉在水面下。",
                        "F_Feature": "一年生沉水草本。葉形變化多端，有線形、湯匙形、披針形、卵形或心形。花穗長度4公分，花朵長度2.5~3.5公分，寬度1.7~1.9公分，每朵花有3片花瓣，形狀類似倒立的雞蛋，上表面呈淡紫色，下表面呈黃色。每朵花有3枚雄蕊及3枚雌蕊，但雌蕊偶有4或6枚。果實長度2~4.5公分，呈窄橢圓形。",
                        "F_Function＆Application": "1. 全草可作土壤改良之用，適應力強，為良好的飼料及綠肥、覆蓋作物。",
                        "F_Code": "",
                        "F_Pic01_ALT": "葉形變化多端",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Hydrochiaritaceae/alismoides/alismoides_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": "6"
                    },
                    {
                        "_id": 18,
                        "﻿F_Name_Ch": "水黃皮",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "九重吹、水流豆、臭腥仔、鳥樹、重吹舅、掛錢樹、野豆",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5808258 24.9981769), (121.582185 24.9984662), (121.5836763 24.9957094), (121.5855083 24.9944599), (121.5867072 24.9945377), (121.5811899 24.9986995))",
                        "F_Location": "臺灣動物區；蕨園；兒童動物區；熱帶雨林區；澳洲動物區；非洲動物區；門內外廣場",
                        "F_Name_En": "Poonga-oil tree、Poongaoil、Poongaoil pongamia、Pongam oiltree、Pongamia",
                        "F_Name_Latin": "Pongamia pinnata",
                        "F_Family": "蝶形花科Papilionaceae",
                        "F_Genus": "水黃皮屬Pongamia",
                        "F_Brief": "分布於印度、馬來西亞、中國南部、琉球群島至澳洲北部。在臺灣主要分布於南部濱海。",
                        "F_Feature": "半落葉中型喬木。整片葉長30公分，寬20公分，分出5~7片小葉，小葉數量通常為奇數，長度6~10公分，寬度3~5公分，呈卵形或長橢圓形，質感類似薄皮革，雙面光滑無毛，邊緣呈波浪狀。花穗長在葉柄與莖的接合處，花朵呈淡紫色。果莢長度4~7公分，寬度2.5~3公分，呈扁平鐮刀狀，質感等同木材，不會開裂，內僅含1顆種子，少有2顆。",
                        "F_Function＆Application": "1. 優良水土保持樹種：其生長快速，生性強健，樹冠傘形，枝葉濃密，抗風、耐乾旱，適合種為海岸護堤、防風林使用。 \n2. 園藝景觀用：樹姿優美，其淡紫色花多成串密生，頗具觀賞價值，為行道樹和公園、庭園景觀樹種。",
                        "F_Code": "",
                        "F_Pic01_ALT": "樹冠茂密可遮蔭乘涼",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Papilionaceae/pinnata/pinnata_1.jpg",
                        "F_Pic02_ALT": "扁平鐮刀狀的果實",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Papilionaceae/pinnata/pinnata_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 19,
                        "﻿F_Name_Ch": "冇骨消",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "臺灣蒴藋、蒴藋、七葉蓮、七珊瑚花、珊瑚花、陸英、接骨草",
                        "F_Geo": "MULTIPOINT ((121.5804577 24.9979216), (121.5805328 24.9959671), (121.5805221 24.9966478))",
                        "F_Location": "臺灣動物區； 蟲蟲探索谷；昆蟲館",
                        "F_Name_En": "Formosanum elderberry",
                        "F_Name_Latin": "Sambucus chinensis",
                        "F_Family": "五福花科 Adoxaceae",
                        "F_Genus": "接骨木屬 Sambucus",
                        "F_Brief": "灌木狀草本植物，分布於中國華東、華中、華南、西南等地的山地，多生長於海拔300~2600公尺的山坡、林下或草叢。",
                        "F_Feature": "多年生常綠灌木，株高3公尺。葉片長度7~20公分，寬度2~5公分，分出3~5片小葉，小葉數量通常為奇數，光滑無毛，上表面顏色較深。花穗具有短毛，部份花朵具有黃色圓柱狀或壺型的蜜腺，花朵僅單一性別，但同一花穗可同時開出雌雄花。果實呈紅色球狀，多肉，果核內有3顆種子。",
                        "F_Function＆Application": "1.蜜源植物：是本土固有植物中最重要的蜜源植物。2.野外求生植物：嫩莖葉可食。",
                        "F_Code": "",
                        "F_Pic01_ALT": "花生長於葉片上方以利花粉傳播",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Adoxaceae/chinensis/chinensis_1.jpg",
                        "F_Pic02_ALT": "",
                        "F_Pic02_URL": "",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    },
                    {
                        "_id": 20,
                        "﻿F_Name_Ch": "臺灣山菊",
                        "F_Summary": "",
                        "F_Keywords": "",
                        "F_AlsoKnown": "橐吳、大吳風草、八角烏、活血蓮、金缽盂、獨角蓮、一葉蓮、大馬蹄香、大馬蹄、鐵冬莧、馬蹄當歸",
                        "F_Geo": "MULTIPOINT ((121.5808258 24.9981769), (121.5805328 24.9959671), (121.5836763 24.9957094))",
                        "F_Location": "蕨園；蟲蟲探索谷；熱帶雨林區",
                        "F_Name_En": "Taiwan leopard plant、Green leopard plant",
                        "F_Name_Latin": "Farfugium japonicum",
                        "F_Family": "菊科Asteraceae",
                        "F_Genus": "山菊屬 Farfugium",
                        "F_Brief": "分布於日本、琉球。本島產於中低海拔山區，陽明山地區及基隆火山群地區均十分常見。",
                        "F_Feature": "莖可能幾乎無毛或具有灰褐色長毛。葉長度6~30公分，寬度4~15公分，呈腎形，葉柄長達10~38公分，從根而非莖長出。開花的莖長度30~75公分，花的排列模式稱為頭狀花序，直徑4~6公分。花形可分為舌頭狀及管狀，舌狀花長度5~6公分，寬度3~4公分，管狀花長度僅11~12公厘。果實長度5~6.5公厘，呈圓柱狀，乾燥，多毛，每顆果實僅有一顆種子，種子長有類似蒲公英的冠毛，長度8~11公厘，呈暗褐色。",
                        "F_Function＆Application": "1. 園藝觀賞：中、大品盆花或庭園、花壇景觀，觀花及觀葉都適合。",
                        "F_Code": "",
                        "F_Pic01_ALT": "花朵相當鮮艷",
                        "F_Pic01_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Asteraceae/Farfugium/Farfugium_1.jpg",
                        "F_Pic02_ALT": "臺灣山菊",
                        "F_Pic02_URL": "http://www.zoo.gov.tw/iTAP/04_Plant/Asteraceae/Farfugium/Farfugium_2.jpg",
                        "F_Pic03_ALT": "",
                        "F_Pic03_URL": "",
                        "F_Pic04_ALT": "",
                        "F_Pic04_URL": "",
                        "F_pdf01_ALT": "",
                        "F_pdf01_URL": "",
                        "F_pdf02_ALT": "",
                        "F_pdf02_URL": "",
                        "F_Voice01_ALT": "",
                        "F_Voice01_URL": "",
                        "F_Voice02_ALT": "",
                        "F_Voice02_URL": "",
                        "F_Voice03_ALT": "",
                        "F_Voice03_URL": "",
                        "F_Vedio_URL": "",
                        "F_Update": "2017/9/4",
                        "F_CID": ""
                    }
                ]
            }
        }
        """#
        return resultJson
    }

    
}
